# Generated by Django 2.1.7 on 2019-03-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuelest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zip',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='quotehistory',
            name='gallons',
            field=models.IntegerField(),
        ),
    ]
